# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# require:
#   - rubocop-slim

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  #EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true
  AutoCorrect: true

Style/FrozenStringLiteralComment:
  Enabled: true

Layout/EmptyLines:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Style/Lambda:
  Enabled: true

Layout/HashAlignment:
  Enabled: true

Bundler/OrderedGems:
  Enabled: true
Layout/LeadingEmptyLines:
  Enabled: true
Layout/MultilineArrayBraceLayout:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  Enabled: true
Layout/SpaceAroundOperators:
  Enabled: true
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/UselessAssignment:
  Enabled: true
Rails/Blank:
  Enabled: true
Rails/FilePath:
  Enabled: true
Rails/HttpStatus:
  Enabled: true
Rails/RootPathnameMethods:
  Enabled: true
Style/Alias:
  Enabled: true
Style/EmptyMethod:
  Enabled: true
Style/GlobalStdStream:
  Enabled: true
Style/NumericLiterals:
  Enabled: true
Style/NumericPredicate:
  Enabled: true
Style/RaiseArgs:
  Enabled: true
Style/RedundantConstantBase:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantSelf:
  Enabled: true
Style/SymbolArray:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space
Layout/TrailingWhitespace:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true
Layout/EmptyLineAfterGuardClause:
  Enabled: true
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: true
Layout/RescueEnsureAlignment:
  Enabled: true
Lint/AmbiguousRegexpLiteral:
  Enabled: true
Layout/FirstHashElementIndentation:
  Enabled: true

Layout/IndentationWidth:
  Enabled: true
  Width: 2  # Default is 2, but explicitly setting it ensures consistency

# For consistent indentation across all Ruby files
Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal  # Use normal indentation (2 spaces)

# Optional: Auto-correct indentation offenses
Layout/IndentationStyle:
  Enabled: true
  IndentationWidth: 2

Layout/ExtraSpacing:
  Enabled: true

# Prefer single-quoted strings when you don't need string interpolation or special symbols.
Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  #EnforcedStyle: double_quotes
  AutoCorrect: true

# Use underscores(_) as thousands separator and separate every 3 digits with them.
Style/NumericLiterals:
  Enabled: true

# Use %w or %W for an array of words.
Style/WordArray:
  Enabled: true

# Use anonymous positional arguments forwarding (*).
Style/ArgumentsForwarding:
  Enabled: true

# Avoid rescuing the Exception class. Perhaps you meant to rescue StandardError?
Lint/RescueException:
  Enabled: true

# Avoid rescuing without specifying an error class.
Style/RescueStandardError:
  Enabled: true

# Keep a blank line before and after private.
Layout/EmptyLinesAroundAccessModifier:
  Enabled: true

# Do not use space inside array brackets.
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: true
  EnforcedStyle: no_space

# Use &:purge as an argument to each instead of a block.
Style/SymbolProc:
  Enabled: true

# Use find_each instead of each.
Rails/FindEach:
  Enabled: true

# Use ENV.fetch('VAR') or ENV.fetch('VAR', nil) instead of ENV['VAR'].
Style/FetchEnvVar:
  Enabled: true

# Freeze mutable objects assigned to constants.
Style/MutableConstant:
  Enabled: true

# Method parameter must be at least 3 characters long.
Naming/MethodParameterName:
  Enabled: true
  MinNameLength: 3

# Use Time.zone.now, Time.current, etc., instead of Time.now.
Rails/TimeZone:
  Enabled: true

# Add a frozen string literal comment to the top of files.
Style/FrozenStringLiteralComment:
  Enabled: true

# Expected 1 empty line between method definitions; found 0.
Layout/EmptyLineBetweenDefs:
  Enabled: true

# Don't use parentheses around an interpolated expression.
Style/RedundantParentheses:
  Enabled: true

# Use _ or _name as an argument name to indicate that it won't be used.
Lint/UnusedMethodArgument:
  Enabled: true